spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bdTaskFlow_PW
    username: postgres
    password: 12345678
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: taskflowpw2024@gmail.com
    password: ctqrtflygfopqbju
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      token:
        secret-key: your-256-bit-secret
        expiration: 3600000 # 1 hora en milisegundos
