spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bdTaskFlow_PW
    username: DylanAriasD
    password: Lolaso0709rico2001.
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db  # Apuntando a la carpeta db de resources donde se encuentran los scripts.
    clean-disabled: false  # Permite limpiar la base de datos (útil para desarrollo, pero desactívalo en producción)

  mail:
    host: smtp.gmail.com
    port: 587
    username: taskflowpw2024@gmail.com
    password: ctqrtflygfopqbju
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    jwt:
      token:
        secret-key: your-256-bit-secret
        expiration: 3600000 # 1 hora en milisegundos

logging:
  level:
    org.flywaydb: DEBUG  # Aumentar nivel de logging para Flyway
    org.springframework.orm.jpa: DEBUG  # Aumentar nivel de logging para JPA
